#!/usr/bin/env bash

set -e

isort --recursive  --force-single-line-imports boxv2 tests
autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place boxv2 tests
black boxv2 tests
isort --recursive boxv2 tests
