#!/usr/bin/env bash

set -e

isort --force-single-line-imports asyncbox tests
autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place --exclude asyncbox/template/** asyncbox tests
black --exclude asyncbox/template asyncbox tests
isort asyncbox tests
