#!/usr/bin/env bash

if [ -f .env ]; then
  source .env
fi

echo using PostgreSQL at $TEST_POSTGRES_DSN
echo using Redis at $TEST_REDIS_DSN

echo testing boxv2 itself
POSTGRES_DSN=$TEST_POSTGRES_DSN REDIS_DSN=$TEST_REDIS_DSN pytest --cov-config=setup.cfg
