#!/usr/bin/env bash

if [ -f .env ]; then
  source .env
fi

echo using PostgreSQL at $TEST_POSTGRES_DSN
echo using Redis at $TEST_REDIS_DSN
echo testing bot template

BOT_NAME=$(openssl rand -hex 16)
python -m  boxv2 -v -p tortoise -p debug -p logger ${BOT_NAME} || exit 1
ln -s ../boxv2 ${BOT_NAME}/boxv2 || exit 1
cd ${BOT_NAME} || exit 1
POSTGRES_DSN=$TEST_POSTGRES_DSN REDIS_DSN=$TEST_REDIS_DSN pytest --cov-config=setup.cfg
EXIT_CODE=$?
cd ..
rm -rf ${BOT_NAME}
if [[ $EXIT_CODE -gt 0 ]]; then exit $EXIT_CODE; fi
