#!/usr/bin/env bash

if [ -f .env ]; then
  source .env
fi

echo testing asyncbox

POSTGRES_DSN="${TEST_POSTGRES_DSN:-$POSTGRES_DSN}"
REDIS_DSN="${TEST_REDIS_DSN:-$REDIS_DSN}"

echo using PostgreSQL at $POSTGRES_DSN
echo using Redis at $REDIS_DSN

pytest --cov-config=setup.cfg ${@}
